// <auto-generated />
namespace CodingCraftoHOMod1Ex1EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mudanca_produto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mudanca_produto));
        
        string IMigrationMetadata.Id
        {
            get { return "202006040130014_mudanca_produto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
