// <auto-generated />
namespace CodingCraftoHOMod1Ex1EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Mudaca_nomidentiy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mudaca_nomidentiy));
        
        string IMigrationMetadata.Id
        {
            get { return "202006011718230_Mudaca_nom-identiy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
